### ISSUE TITLE
README.md 업데이트 했습니다!

### ISSUE THREAD

**Issue by hyeonjikim-kr** [leh0818/Creative_CCPS#14]
@minjoo-6 @dbwodnjs902 @leh0818 
학번 입력해주세요!

**Comment by leh0818** [comment]
민주랑 재원이 수정하면 pull request 받아줄게여

**Comment by hyeonjikim-kr** [comment]
@leh0818 조장님 ! 조장님 이름을 맨 위로 가게 수정해주실래여???? 왜냐면 조장님이 조장님이시니까....

**Comment by leh0818** [comment]
스터디 끝나고 할게여!
