### ISSUE TITLE
0606 회의 공지

### ISSUE THREAD

**Issue by leh0818** [leh0818/Creative_CCPS#25]
회의 시간 : 오후 7시 반         
zoom 주소 : 

다들 내일 회의 주제인 웹페이지 모양?에 대해 쪼꼼씩 생각해보아여👏

**Comment by hyeonjikim-kr** [comment]
그리고 깃허브랑 깃허브 홈페이지 공부도 해볼까요~?

**Comment by leh0818** [comment]
어떤 공부?
