### ISSUE TITLE
금일 (06/20) 회의 안건

### ISSUE THREAD

**Issue by hyeonjikim-kr** [leh0818/Creative_CCPS#41]
1. 페이지 디자인 아이디어
2. 결과 문구 생각하기
3. URL 복사기능 공부 (java랑 연관)

개발상황 보고 앞으로의 진행방향 결정하기!

**Comment by leh0818** [comment]
> 1. 페이지 디자인 아이디어
> 2. 결과 문구 생각하기
> 3. URL 복사기능 공부 (java랑 연관)
> 
> 개발상황 보고 앞으로의 진행방향 결정하기!

3번은 javascript 메몸ㅁ메모,,
공유하기 위한 url 복사다!
