### ISSUE TITLE
NEW RULE!!!!!

### ISSUE THREAD

**Issue by hyeonjikim-kr** [leh0818/Creative_CCPS#44]
CSS

meta charset="utf-8" 
head에 무조건 쓰기!
----------------------------------------------------------------------

이것은 유니코드 문자셋인데 영어는 물론 한글, 일본어, 중국어등 전세계 대부분의 언어를 표현해주는 문자셋이라고 하네요!

크롬뿐만아니라 인터넷익스플로어에서 열려면 일단 사용하는게 좋을듯 합닌다!!!!!!!!!

**Comment by hyeonjikim-kr** [comment]
@minjoo-6 @leh0818 
보시오!

**Comment by minju-6** [comment]
좋은 정보이네요 ~!
